import axios from "axios";
import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests, { BASE_URL } from "../utils/requests";

export default function Home({ results }) {
	return (
		<div>
			<Head>
				<title>Hulu 1.0</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link
					rel="apple-touch-icon"
					sizes="180x180"
					href="/apple-touch-icon.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="32x32"
					href="/favicon-32x32.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="16x16"
					href="/favicon-16x16.png"
				/>
				<link rel="manifest" href="/site.webmanifest" />
				<link
					rel="mask-icon"
					href="/safari-pinned-tab.svg"
					color="#5bbad5"
				/>
				<meta name="msapplication-TileColor" content="#da532c" />
				<meta name="theme-color" content="#ffffff" />
			</Head>
			<Header />
			<Nav />
			<Results results={results} />
		</div>
	);
}

export const getServerSideProps = async cxt => {
	const genre = cxt.query.genre;

	const { data } = await axios.get(
		`${BASE_URL}${requests[genre]?.url ?? requests.trending.url}`
	);

	return {
		props: { results: data.results },
	};
};
