import axios from "axios";
import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests, { BASE_URL } from "../utils/requests";

export default function Home({ results }) {
	return (
		<div>
			<Head>
				<title>Hulu 0.0</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<Nav />
			<Results results={results} />
		</div>
	);
}

export const getServerSideProps = async cxt => {
	const genre = cxt.query.genre;

	const { data } = await axios.get(
		`${BASE_URL}${requests[genre]?.url ?? requests.trending.url}`
	);

	return {
		props: { results: data.results },
	};
};
